
#define WIFI_SSID "SSID"
#define WIFI_PASSWORD "PASSWORD"
#define IMAGE_SERVER_HOST "HOST"
#define IMAGE_SERVER_HTTP_PORT 62100
#define IMAGE_SERVER_CONTROL_PORT 62101

#define DEFAULT_UPLOAD_INTERVAL (10*60*1000)
#define COMMAND_CHANNEL_RETRY_INTERVAL (20*1000)
