
#define WIFI_SSID "Wowcitos"
#define WIFI_PASSWORD "_Wowcito1531!."
#define IMAGE_SERVER_HOST "broker.growthmonitor.cl"
#define IMAGE_SERVER_HTTP_PORT 62100
#define IMAGE_SERVER_CONTROL_PORT 62101
#define IMAGE_SERVER_API_KEY "ApiKey"

#define DEFAULT_UPLOAD_INTERVAL (10*60*1000)
#define COMMAND_CHANNEL_RETRY_INTERVAL (20*1000)
